### ISSUE TITLE
load-data.sh fails on the first run

### ISSUE THREAD

**Issue by wwilkins** [4clojure/4clojure#255]
The first time running load-data.sh resulted in the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Leiningen
Caused by: java.lang.ClassNotFoundException: Leiningen
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

The second run completed successfully without making any other changes to the environment.

**Comment by kazesberger** [comment]
I think this is fixed in case this ever was an issue. cannot reproduce.
