### ISSUE TITLE
There is a Exception when i am running the file "load-data.sh".

### ISSUE THREAD

**Issue by dlnufox** [4clojure/4clojure#259]
Exception in thread "main" java.lang.NoClassDefFoundError: You're
Caused by: java.lang.ClassNotFoundException: You're
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: You're. Program will exit.

**Comment by amcnamara** [comment]
Very odd, looks like there was an error with the class loader reading or parsing some string in the code.  Regardless this seems transient, and I wasn't able to repro this issue on a fresh clone so I'll close.  Sorry this didn't get resolution sooner, if you have a way to repro this issue please let me know!
