### ISSUE TITLE
Upgrade Dependency congomongo?

### ISSUE THREAD

**Issue by slide-rule** [4clojure/4clojure#291]
After checking forking 4clojure to hack around a bit, I spent a lot of time on the following error:
```
Exception in thread "main" com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "The field 'force' is not valid for an index specification. Specification: { name: \"solved_1\", ns: \"4clojure.problems\", force: true, unique: false, key: { solved: 1 } }" , "code" : 197 , "codeName" : "InvalidIndexSpecificationOption"}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.DBCollectionImpl.createIndex(DBCollectionImpl.java:497)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:762)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:891)
	at somnium.congomongo$add_index_BANG_.doInvoke(congomongo.clj:445)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at foreclojure.mongo$prepare_problems.invoke(mongo.clj:19)
	at foreclojure.mongo$prepare_mongo.invoke(mongo.clj:65)
	at user$eval51.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$eval_opt.invoke(main.clj:297)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:427)
	at clojure.lang.AFn.applyToHelper(AFn.java:172)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
```
Turns out the version of mongo I downloaded (3.4.2) didn't play well with the version of congomongo in the project (I believe congomongo version 0.2.0 removes the 'force' option. I upgraded to 0.5.0 and things seem to be working so far...). 

Anyway, I know there's not a ton of activity on this repository these days, but I figured I'd chime in.

**Comment by Cyrus-Malekani** [comment]
Thanks for the heads-up had the same problem!
