### ISSUE TITLE
load.sh fails with Mongo error "Invalid system namespace: 4clojure.system.indexes"

### ISSUE THREAD

**Issue by jos-eph** [4clojure/4clojure#326]
I'm unable to run the load.sh script successfully in Linux.

The script creates problems and seqs collections in a 4clojure database, both of which have data as verified by mongosh. 

But then, the creation script fails with this error. Any thoughts?

Exception in thread "main" com.mongodb.MongoException: Invalid system namespace: 4clojure.system.indexes
	at com.mongodb.CommandResult.getException(CommandResult.java:87)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:121)
	at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:131)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:155)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:138)
	at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:261)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:365)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:436)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:515)
	at somnium.congomongo$add_index_BANG_.doInvoke(congomongo.clj:445)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at foreclojure.mongo$prepare_problems.invoke(mongo.clj:19)
	at foreclojure.mongo$prepare_mongo.invoke(mongo.clj:65)
	at user$eval4914.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$eval_opt.invoke(main.clj:297)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:427)
	at clojure.lang.AFn.applyToHelper(AFn.java:172)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)

**Comment by nalingupta1** [comment]
I see a similar problem. I'm using Cent OS 8 :
`
Exception in thread "main" com.mongodb.MongoException: cannot write to '4clojure.system.indexes'
        at com.mongodb.CommandResult.getException(CommandResult.java:87)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:121)
        at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:131)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:155)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:138)
        at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:261)
        at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:365)
        at com.mongodb.DBCollection.createIndex(DBCollection.java:436)
        at com.mongodb.DBCollection.ensureIndex(DBCollection.java:515)
        at somnium.congomongo$add_index_BANG_.doInvoke(congomongo.clj:445)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at foreclojure.mongo$prepare_problems.invoke(mongo.clj:19)
        at foreclojure.mongo$prepare_mongo.invoke(mongo.clj:65)
        at user$eval4914.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.eval(Compiler.java:6477)
        at clojure.core$eval.invoke(core.clj:2797)
        at clojure.main$eval_opt.invoke(main.clj:297)
        at clojure.main$initialize.invoke(main.clj:316)
        at clojure.main$null_opt.invoke(main.clj:349)
        at clojure.main$main.doInvoke(main.clj:427)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.lang.Var.invoke(Var.java:427)
        at clojure.lang.AFn.applyToHelper(AFn.java:172)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
`

**Comment by Grant-decaying** [comment]
the truth is known https://nivo-react-questioning.github.io/TOmGuiVcGkGflKYPSw0qVYuZoNj/
